/* eslint-disable import/no-anonymous-default-export */
// @flow
export default {
  common: {
    homeBreadCrumb: 'Virtual Walk Through',
    dailyWalkThrough: 'Daily Walk Through',
    saleWalkThrough: 'Sale Walk Through',
    checkWalkThrough: 'Check Walk Through',
    copartSelectWalkThrough: 'Copart Select Walk Through',
    dwt: 'Daily Walk Through',
    swt: 'Sale Walk Through',
    nmvtis: 'NMVTIS',
    iwt: '360 Walk Through',
    eswt: 'Engine Sound Walk Through',
    roleErrMsg: 'User is not authorized to view tile',
    lastModified: 'Last Modified',
    dateCreated: 'Date Created',
    fullScreen: 'Full Screen',
    unknownError: 'Unknown Error',
    advanceCharges: 'Advance Charges',
    issues: 'Issues',
    issuesView: 'Issues',
    SOLotStage50Error: 'Cannot create/update service order when the lot stage is greater than 50',
    createLotStage50Error: 'Action is unavailable. Please remove lot from auction.',
    deleteLotStage50Error: 'Action is unavailable. Please remove lot from auction.',
    imageUploadSuccess: 'Image uploaded successfully. Refresh after few minutes to see the changes',
    imageUploadFailure: 'Image upload failed.'
  },
  listView: {
    make: 'Make',
    year: 'Year',
    homeBreadCrumb: 'Virtual Walk Through',
    color: 'Color',
    row: 'Row',
    itemNumber: 'Item Number',
    titleType: 'Title Group',
    yard: 'Yard',
    seller: 'Seller',
    model: 'Model',
    reviewStatus: 'Review Status',
    receivedOn: 'Received On',
    receivedBy: 'Received By',
    saleDate: 'Sale Date',
    actions: 'Actions',
    column_yardNumber: 'Yard',
    column_pendingActions: 'Pending Actions',
    column_pendingReview: 'Pending Review',
    column_reviewStatus: 'Review Status',
    column_receivedDate: 'Received Date',
    column_receivedBy: 'Received By',
    column_titleGroup: 'Title Group',
    column_isOverdue: 'Is Overdue',
    column_sellerName: 'Seller Name',
    column_sellerCompanyName: 'Seller Company Name',
    column_damage: 'Damage',
    column_saleDate: 'Sale Date',
    column_reviewedBy: 'Reviewed By',
    column_approvedBy: 'Approved By',
    column_reviewCompleteBy: 'Review Complete By',
    column_issueTypes: 'Issue Types',
    column_issueFields: 'Issue Fields',
    column_fuelTypeDesc: 'Fuel Type',
    column_vehicleTypeDesc: 'Vehicle Type',
    column_walkthroughEligibleDate: 'Walkthrough Eligible Date',
    column_lastReviewed: 'Last Reviewed',
    column_sellerCompany: 'Seller Company',
    column_sellerCode: 'Seller Company Code',
    column_state: 'P/U Location State',
    column_zipcode: 'P/U Location Zip',
    column_locationName: 'P/U Location Name',
    column_facilityId: 'Facility Id',
    column_paymentMethod: 'Payment Type',
    column_earliestDueDate: 'Earliest Due Date',
    column_formSubmittedOn: 'Form Submitted On',
    column_rejectReason: 'Rejection Reason',
    column_copartSelectCode: 'Copart Select',
    rejectReason: 'Rejection Reason',
    pendingReview: 'Pending Review',
    awaitingInitialReview: 'Awaiting Initial Review',
    vehicleTypeTooltip: 'Pending Vehicle Type Review',
    damageTooltip: 'Pending Damage Review',
    keysDriveTooltip: 'Pending Keys And Drive Review',
    odometerTooltip: 'Pending Odometer Review',
    imagesTooltip: 'Pending Images Review',
    overdueTooltip: 'Overdue',
    awaitingApprovalTooltip: 'Awaiting Approval Status',
    wrongVehicleTooltip: 'Wrong Vehicle',
    reviewCompletedTooltip: 'Review Completed Today',
    cleanTitleTooltip: 'Clean Title',
    salvageTitleTooltip: 'Salvage Title',
    review: 'Review',
    damage: 'Damage',
    vehicleDetails: 'Vehicle Details',
    keysDrive: 'Keys And Drive',
    odometer: 'Odometer',
    images: 'Images',
    reviewDamage: 'Review Damage',
    reviewVehicleDetails: 'Review Vehicle Details',
    reviewKeysDrive: 'Review Keys And Drive',
    reviewOdometer: 'Review Odometer',
    reviewImages: 'Review Images',
    dueDate: 'Due Date',
    searchText: 'Search by Lot Number',
    dwtEligibleOn: 'DWT Eligible Date',
    towType: 'Tow Type',
    tripVerifiedDate: 'Walkthrough Eligible Date',

    dwtEligibleDateUtc: 'DWT Eligible Date',
    issueApprover: 'Issue Approved By',
    issueCreatedBy: 'Issue Created By',
    issueFields: 'Issue Fields',
    issueOriginalValue: 'Issue Original Value',
    issueRecommendedValue: 'Issue Recommended Value',
    issueReviewed: 'Issue Reviewed On',
    issueStatus: 'Issue Status',
    issueType: 'Issue Type',
    vwtType: 'VWT Type',
    sellerCompanyId: 'Seller Company Id',
    sellerCompany: 'Seller Company',
    sellerId: 'Seller Id',
    status: 'Status',
    yardNumber: 'Yard Number',
    lotNumber: 'Lot Number',
    column_issueApprover: 'Issue Approved By',
    column_issueStatus: 'Issue Status',
    column_issueType: 'Issue Type',
    column_issueAcknowledgeFlag: 'Issue Acknowledge Flag',
    column_issueCreatedBy: 'Issue Created By',
    issueComments: 'Issue Comments',
    issueRejectedComments: 'Additional Comments',
    issueAction: 'Action',
    acknowledgeActions: 'Acknowledge Issue',
    dwtRejectedIssues: 'DWT Rejected Issues',
    swtRejectedIssues: 'SWT Rejected Issues',
    nmvtisRejectedIssues: 'NMVTIS Rejected Issues',
    acwRejectedIssues: 'Advance Charges Rejected Issues',
    totalRejectedIssues: 'Total Rejected Issues',
    iwtRejectedIssues: '360 Walk Through Rejected Issues',
    eswtRejectedIssues: 'Engine Sound Walk Through Rejected Issues',
    column_vwtType: 'VWT Type',
    awaitingActionTooltip: 'Awaiting Action',
    locationName: 'Pickup Location',
    state: 'State',
    zipcode: 'Zipcode',
    facilityId: 'Yard Number',
    formSubmittedOn: 'Form Submitted On',
    driverEnteredAmount: 'Driver Entered Amount',
    cfrClearedCharges: 'CFR Cleared Charges',
    sellerCode: 'Seller Code',
    paymentMethod: 'Driver Pay Method',
    iwtReviewPending: 'Review Pending',
    iwtReviewComplete: 'Review Complete',
    yardsSelected: 'Selected Yard(s)'
  },
  reviewSteps: {
    dwt: {
      receiverNotes: 'Receiver Notes',
      receiverNotesBody:
        'Any image related issues should be marked through the issues button below the image. Simply, click the issues button and select the relevant from the dropdown. If the issue can be solved through simple image editing, make all necesarry changes the “Edit” button below the image',
      step1Instruction: 'Instructions',
      step1InstructionBody:
        'Review the receiving data below with the images on the left and verify the vehicle type, make, model, color trim, and year. If there is an inconsistency in the data or the data cannot be reliably verified, please mark the specific field as incorrect and attempt to provide a correct value recommendation. If a recomendation cannot be determined, give a short explanation of the issue instead. Any image related issues should be marked through the issues button below the image. Simply, click the issues button and select the relevant from the dropdown.',
      sellerExceptions: 'Seller Exceptions',
      sellerExceptionsBody:
        'Any image related issues should be marked through the issues button below the image. Simply, click the issues button and select the relevant from the dropdown. If the issue can be solved through simple image editing, make all necesarry changes the “Edit” button below the image.',
      vehicleType: 'Vehicle Type',
      make: 'Make',
      model: 'Model',
      color: 'Color',
      primaryType: 'Primary Damage',
      secondaryDamage: 'Secondary Damage',
      keysStatus: 'Keys Status',
      driveStatus: 'Drive Status',
      odometer: 'Odometer',
      wrongVehicle: 'Wrong Vehicle',
      serviceOrdersSuggestions: 'Service Orders Suggestions',
      serviceOrdersComments: 'Service Orders Comments',
      receivingData: 'Receiving Data',
      hoodCheck: 'Hood Check',
      receiver: 'Receiver',
      sellerName: 'Seller Name',
      estRetailValue: 'EST.Retail Value',
      vin: 'VIN',
      keyStatus: 'Key Status',
      repairCost: 'Repair Cost',
      facility: 'Facility',
      saleStatus: 'Sale Status',
      virtualSaleYard: 'Virtual Sale Yard',
      primaryDamage: 'Primary Damage',
      nmvtisStatus: 'NMVTIS Status',
      specialNotes: 'Special Notes',
      towType: 'Tow Type',
      titleState: 'Title State / Type',
      missingParts: 'Missing Parts',
      currentBid: 'Current Bid',
      serviceOrderSnapshots: 'Service Order Snapshots',
      saleAuctionDateTime: 'Sale/Auction Date Time',
      itemGridRow: 'Item #/Grid Row',
      lotInfo: 'Lot Information',
      seller: 'Seller',
      sellerAddress: 'Seller Address',
      adjusterName: 'Adjuster Name',
      pickedUp: 'Picked Up',
      advanceCharges: 'Advance Charges',
      advanceChargesLabel: 'Charges',
      odometerBrand: 'Odometer Brand',
      sellerType: 'Seller Type',
      receiverNotes: 'Receiver Notes',
      paymentMethod: 'Payment Method',
      imagesAndVehicleDetails: 'Images and Vehicle Details',
      damage: 'Damage',
      keysDriveAndOdometer: 'Keys, Drive and Odometer',
      titlependingFromStateFlag: 'Title Pending From State'
    },
    swt: {
      titleType: 'Title Group',
      serviceOrderLabel: 'Service Orders'
    },
    nmvtis: {
      nmvtis: 'NMVTIS'
    },
    advanceCharges: {
      tow: 'Tow',
      labor: 'Labor',
      gate: 'Gate/Yard',
      storageFromDate: 'Storage From Date',
      storageToDate: 'Storage To Date',
      storageAmount: 'Storage Amount',
      storageRate: 'Storage Rate',
      secondStorageFromDate: 'Second Storage From Date',
      secondStorageToDate: 'Second Storage To Date',
      secondStorageAmount: 'Second Storage Amount',
      secondStorageRate: 'Second Storage Rate',
      negotiatedStorage: 'Flat/Negotiated Storage',
      estimatingFee: 'Teardown/Estimating Fee',
      miscFee: 'Misc Fee',
      miscChargesDescription: 'Misc Charges Description',
      tax: 'Tax',
      total: 'Total',
      storageOneTotal: 'Storage 1 Total',
      storageTwoTotal: 'Storage 2 Total',
      miscellaneousFee: 'Miscellaneous Fee',
      paymentType: 'Payment Method',
      totalAmount: 'Total Card Amount',
      payableTo: 'Payable To',
      checkNum: 'Check Number',
      cardAuth: 'Card Auth',
      lastFourDigits: 'Last 4 Digits',
      flatNegotiatedStorage: 'Flat/Negotiated Storage',
      teardownEstimatingFee: 'Teardown/Estimating Fee',
      missingDocument: 'Missing Document',
      fieldName: 'Field Name',
      documentType: 'Document Type',
      issueType: 'Issue Type',
      comments: 'Comments',
      status: 'Status',
      rejectionComment: 'Rejection Comment',
      chargesDescriptions: 'Charges Descriptions',
      paymentInformation: 'Payment Information',
      chargesReview: 'Charges Review',
      reviewSummary: 'Review Summary',
      dataIssues: 'Data Issues',
      documentIssues: ' Document Issues',
      missingDocuments: 'Missing Documents',
      totalCheckAmount: 'Total Check Amount',
      missingDocument: 'Missing Document',
      fileGalleryAdvanceCharges: 'Trip Verification Documents'
    },
    cwt: {
      paymentType: 'Payment Type',
      paymentDetails: 'Payment Details',
      cfrClearedCharges: 'CFR Cleared Charges',
      driverAddedCharges: 'Driver Entered Charges',
      capturedDetails: 'Captured Details',
      confirmDetails: 'Confirm Details',
      checkYardNumber: 'Check Yard Number',
      checkAmount: 'Check Amount',
      checkDate: 'Check Date',
      checkNumber: 'Check Number',
      warningMessage:
        'The number of payment documents do not match with the checks to confirm. Please verify once again before you proceed to save.',
      addAdditionalCheck: 'Add Additional Check',
      raisedIssueText: 'There are raised issues which are unsaved. On confirming, it will be discarded',
      paidByCheck: 'Paid by Check',
      cantRaiseIssue: 'Cannot raise issue if the lot is not paid by Check',
      checkSubmitSuccess: 'Check has been submitted successfully',
      discardText: 'Are you sure you want to proceed?',
      discardSubText: 'This can not be undone.',
      confirmBeforeSaveText:
        'Since there are no issues and no new Check(s) added, submitting this lot will move it to Review Complete.',
      confirmBeforeSaveSubText: 'Are you sure you want to proceed?',
      copyAll: 'Copy All',
      copy: 'Copy',
      removeCheck: 'Remove This Check',
      allVisitedNotification: 'Please view all check images before submission'
    },
    iwt: {
      cantCreateSO: 'Approving issues will not create service orders when the lot stage is greater than or equal to 50',
      discardText: 'Are you sure you want to proceed?',
      discardSubText: 'This can not be undone.'
    },
    eswt: {
      discardText: 'Are you sure you want to proceed?',
      discardSubText: 'This can not be undone.'
    },
    cswt: {
      dataIssueCannotApprove: 'Data issue cannot be approved as the Lot has Auction date',
      imageEditsIssueCannotApprove: 'Image edits issue cannot be approved as the Lot is in auction',
      imageIssueCannotApprove: 'Image issue cannot be approved as the Lot state is moved from ready from auction',
      imageIssueWarning: 'Due to this action, Auction date will be removed. Please confirm to proceed'
    },
    discardChanges: 'Discard Changes',
    prevLot: 'Save & Prev Lot',
    prevStep: 'Save & Prev Step',
    nextStep: 'Save & Next Step',
    nextLot: 'Save & Next Lot',
    skipToNext: 'Skip & Next Lot',
    raiseIssue: 'Raise Issue',
    issueDetails: 'Issue Details',
    save: 'save',
    imageIssues: 'Image Issues',
    dataIssues: 'Data Issues',
    serviceOrders: 'Service Orders',
    imageNum: 'Image#',
    issueType: 'Issue Type',
    comments: 'Comments',
    approve: 'Approve?',
    images: 'Images',
    report: 'Report',
    doNotReport: 'Do Not Report',
    saleTitle: 'Sale Document',
    approverView: 'Approver View',
    reviewerView: 'Reviewer View',
    raiseIssue: 'Raise Issue',
    deleteIssue: 'Delete Issue',
    issueType: 'Issue Type',
    issueComments: 'Issue Comments',
    customNotes: 'Custom Notes',
    failedToLoadData: 'Failed to load data',
    failedToSaveData: 'Failed to save data',
    failedToFetchNextLot: 'Failed to fetch next lot',
    nextLotFetchSuccess: 'Fetched next lot successfully',
    dataFetchSuccess: 'Fetched Data successfully',
    dataSaveSuccess: 'Data saved successfully',
    fetchingData: 'Fetching Data',
    determiningNextLot: 'Determining Next Lot',
    redirectingToNextLot: 'Redirecting to Next Lot',
    advanceChargesDocumentTitle: 'Advance Charges Invoice',
    approverComments: 'Approver Comments',
    rejectionReason: 'Rejection Reason',
    additionalComment: 'Additional Comment',
    paymentInstrument: 'Payment Instrument',
    pickupOrders: 'Pickup Orders',
    deleteMSD: 'Remove Issue',
    uploadFileSuccess: 'File Uploaded Successfully',
    uploadFileFailure: 'Failed to upload file',
    sellerDetails: 'Seller Details',
    sellerName: 'Seller Name :',
    sellerCode: 'Seller Code :',
    uploadDialogTitle: 'Upload Files',
    uploadImageTitle: 'Upload Image',
    uploadImageWarning: 'Can upload only one image at a time',
    documentType: 'Document type',
    selectDocumentType: 'Select Your Document Type',
    changeDocumentType: 'Change Document Type',
    selectDocumentType: 'Select the document type',
    seller: 'Seller',
    readOnlyNotificationMessage: 'Functionality is disabled currently',
    lotsLeft: 'Lots Left',
    skipToNextLotSubtext: 'Your unsaved changes will be discarded',
    images360: '360 Images',
    discardText: 'Are you sure you want to proceed?',
    discardSubText: 'This can not be undone.',
    switchToHD: 'Switch To HD',
    somethingWentWrong: 'Something went wrong',
    fetchDataFailure: 'Failed to load request data.',
    imageEditingIssues: 'Image Editing Issues'
  },
  damageFieldsErrorText: 'Primary damage and secondary damage fields cannot be same',
  currentlyWorking: 'Currently Working',
  advanceCharges: 'ADVANCE CHARGES',
  paymentInstrument: 'PAYMENT INSTRUMENT',
  DAT: 'Data Issues',
  MSD: 'Missing Documents',
  DOC: 'Document Issues',
  ADVCI: 'Advance Charges Invoice',
  PAYIN: 'Payment Instrument',
  ADVANCE_CHARGES: 'Advance Charges Invoice',
  ADVANCE_CHARGE_RECEIPT: 'Payment Instrument',
  PICKUP_ORDER: 'Pickup Order',
  IMAGE_360: '360 Images',
  EXT360: 'Exterior 360',
  INT360: 'Interior 360',
  IMAGE: 'Images'
}
